import {
  ApplicationDetail,
  UsersInfo,
} from '../shared/intserfaces/users.intserfaces';

export const jobApplicants: ApplicationDetail[] = [
  {
    id: '123',
    candidate: 'John Doe',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '75000',
    source: 'LinkedIn',
    phone: '+1-555-123-4567',
    email: 'john.doe@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '133',
    candidate: 'Jane Smith',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '65000',
    source: 'Indeed',
    phone: '+1-555-987-6543',
    email: 'jane.smith@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '155',
    candidate: 'Alice Johnson',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '90000',
    source: 'Referral',
    phone: '+1-555-246-8135',
    email: 'alice.johnson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '332',
    candidate: 'Bob Williams',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '55000',
    source: 'Job Fair',
    phone: '+1-555-369-2580',
    email: 'bob.williams@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '221',
    candidate: 'Charlie Brown',
    experience: '4',
    noticePeriod: '45',
    currentCTC: '70000',
    source: 'Company Website',
    phone: '+1-555-147-2589',
    email: 'charlie.brown@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '111',
    candidate: 'Diana Clark',
    experience: '6',
    noticePeriod: '30',
    currentCTC: '85000',
    source: 'LinkedIn',
    phone: '+1-555-753-9514',
    email: 'diana.clark@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '099',
    candidate: 'Edward Davis',
    experience: '8',
    noticePeriod: '90',
    currentCTC: '110000',
    source: 'Recruiter',
    phone: '+1-555-951-7532',
    email: 'edward.davis@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '101',
    candidate: 'Fiona Evans',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '60000',
    source: 'Job Board',
    phone: '+1-555-357-9513',
    email: 'fiona.evans@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '999',
    candidate: 'George Foster',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '80000',
    source: 'Employee Referral',
    phone: '+1-555-159-7532',
    email: 'george.foster@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '187',
    candidate: 'Hannah Green',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '50000',
    source: 'University Career Fair',
    phone: '+1-555-753-1597',
    email: 'hannah.green@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '190',
    candidate: 'Ian Harris',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '95000',
    source: 'LinkedIn',
    phone: '+1-555-951-3575',
    email: 'ian.harris@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '174',
    candidate: 'Julia Jackson',
    experience: '4',
    noticePeriod: '45',
    currentCTC: '72000',
    source: 'Indeed',
    phone: '+1-555-357-9515',
    email: 'julia.jackson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '167',
    candidate: 'Kevin King',
    experience: '6',
    noticePeriod: '30',
    currentCTC: '88000',
    source: 'Company Website',
    phone: '+1-555-159-3575',
    email: 'kevin.king@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '157',
    candidate: 'Laura Lee',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '62000',
    source: 'Job Fair',
    phone: '+1-555-753-9517',
    email: 'laura.lee@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '181',
    candidate: 'Michael Moore',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '78000',
    source: 'Referral',
    phone: '+1-555-951-7539',
    email: 'michael.moore@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '771',
    candidate: 'Nancy Nelson',
    experience: '8',
    noticePeriod: '60',
    currentCTC: '105000',
    source: 'LinkedIn',
    phone: '+1-555-357-1597',
    email: 'nancy.nelson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '149',
    candidate: 'Oscar Oliver',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '52000',
    source: 'Job Board',
    phone: '+1-555-159-3577',
    email: 'oscar.oliver@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '009',
    candidate: 'Patricia Parker',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '86000',
    source: 'Recruiter',
    phone: '+1-555-753-3579',
    email: 'patricia.parker@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '006',
    candidate: 'Quentin Quinn',
    experience: '4',
    noticePeriod: '30',
    currentCTC: '70000',
    source: 'Company Website',
    phone: '+1-555-951-1599',
    email: 'quentin.quinn@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '002',
    candidate: 'Rachel Ross',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '92000',
    source: 'LinkedIn',
    phone: '+1-555-357-3579',
    email: 'rachel.ross@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '003',
    candidate: 'Samuel Scott',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '58000',
    source: 'Job Fair',
    phone: '+1-555-159-1599',
    email: 'samuel.scott@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '088',
    candidate: 'Tina Turner',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '76000',
    source: 'Referral',
    phone: '+1-555-753-1601',
    email: 'tina.turner@email.com',
    status: 'on hold',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
  {
    id: '005',
    candidate: 'Ulysses Underwood',
    experience: '9',
    noticePeriod: '90',
    currentCTC: '120000',
    source: 'Recruiter',
    phone: '+1-555-951-3581',
    email: 'ulysses.underwood@email.com',
    status: 'upCommingInterview',
    screeningDetails: [
      {
        currentlyWorking: 'string',
        experience: 'string',
        companyName: 'string',
        noticePeriod: 'string',
        currentCTC: 'string',
        expectedCTC: 'string',
        project: 'string',
      },
    ],
    interviewDetails: [
      {
        interviewType: 'Face to Face',
        interviewer: 'Daniel Joseph',
        date: '12/03/2024',
        time: '3:00 PM - 4:00 PM',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '655',
    candidate: 'Aswin Krishnan',
    experience: '9',
    noticePeriod: '90',
    currentCTC: '120000',
    source: 'Recruiter',
    phone: '+1-555-951-3581',
    email: 'Aswin.underwood@email.com',
    status: 'upCommingInterview',
    screeningDetails: [
      {
        currentlyWorking: 'string',
        experience: 'string',
        companyName: 'string',
        noticePeriod: 'string',
        currentCTC: 'string',
        expectedCTC: 'string',
        project: 'string',
      },
    ],
    interviewDetails: [
      {
        interviewType: 'Face to Face',
        interviewer: 'Daniel Joseph',
        date: '12/03/2024',
        time: '3:00 PM - 4:00 PM',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '007',
    candidate: 'Victoria Vaughn',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '54000',
    source: 'University Career Fair',
    phone: '+1-555-357-1601',
    email: 'victoria.vaughn@email.com',
    status: 'on hold',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '000',
    candidate: 'William White',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'william.white@email.com',
    status: 'shortlisted',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '121',
    candidate: 'Arjun',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'shortlisted',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '453',
    candidate: 'Shalini',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'feedback',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
  {
    id: '345',
    candidate: 'Shanu',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'feedback',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
];

export const demoUsersInfo: UsersInfo[] = [
  {
    id: '122',
    userName: 'John Doe',
    role: 'SuperAdmin',
    designation: 'Chief Technology Officer',
    phoneNumber: '+1 (555) 123-4567',
    emailId: 'john.doe@company.com',
    profileImage:
      'https://images.pexels.com/photos/1462980/pexels-photo-1462980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1  ',
  },
  {
    id: '133',
    userName: 'Jane Smith',
    role: 'HrManager',
    designation: 'Senior HR Manager',
    phoneNumber: '+1 (555) 234-5678',
    emailId: 'jane.smith@company.com',
    profileImage:
      'https://images.pexels.com/photos/3779760/pexels-photo-3779760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '111',
    userName: 'Mike Johnson',
    role: 'Interviewer',
    designation: 'Senior Software Engineer',
    phoneNumber: '+1 (555) 345-6789',
    emailId: 'mike.johnson@company.com',
    profileImage:
      'https://images.pexels.com/photos/2080383/pexels-photo-2080383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '144',
    userName: 'Sarah Williams',
    role: 'Recruiter',
    designation: 'Talent Acquisition Specialist',
    phoneNumber: '+1 (555) 456-7890',
    emailId: 'sarah.williams@company.com',
    profileImage:
      'https://images.pexels.com/photos/1188047/pexels-photo-1188047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '155',
    userName: 'David Brown',
    role: 'Department Head',
    designation: 'Head of Engineering',
    phoneNumber: '+1 (555) 567-8901',
    emailId: 'david.brown@company.com',
    profileImage:
      'https://images.pexels.com/photos/17718199/pexels-photo-17718199/free-photo-of-man-with-black-hair.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
];
