import {
  ApplicationDetail,
  Job,
  UsersInfo,
} from '../shared/intserfaces/users.intserfaces';

export const jobApplicants: ApplicationDetail[] = [
  {
    id: '123',
    candidate: 'John Doe',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '75000',
    source: 'LinkedIn',
    phone: '+1-555-123-4567',
    email: 'john.doe@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '133',
    candidate: 'Jane Smith',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '65000',
    source: 'Indeed',
    phone: '+1-555-987-6543',
    email: 'jane.smith@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '155',
    candidate: 'Alice Johnson',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '90000',
    source: 'Referral',
    phone: '+1-555-246-8135',
    email: 'alice.johnson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '332',
    candidate: 'Bob Williams',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '55000',
    source: 'Job Fair',
    phone: '+1-555-369-2580',
    email: 'bob.williams@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '221',
    candidate: 'Charlie Brown',
    experience: '4',
    noticePeriod: '45',
    currentCTC: '70000',
    source: 'Company Website',
    phone: '+1-555-147-2589',
    email: 'charlie.brown@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '111',
    candidate: 'Diana Clark',
    experience: '6',
    noticePeriod: '30',
    currentCTC: '85000',
    source: 'LinkedIn',
    phone: '+1-555-753-9514',
    email: 'diana.clark@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '099',
    candidate: 'Edward Davis',
    experience: '8',
    noticePeriod: '90',
    currentCTC: '110000',
    source: 'Recruiter',
    phone: '+1-555-951-7532',
    email: 'edward.davis@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '101',
    candidate: 'Fiona Evans',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '60000',
    source: 'Job Board',
    phone: '+1-555-357-9513',
    email: 'fiona.evans@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '999',
    candidate: 'George Foster',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '80000',
    source: 'Employee Referral',
    phone: '+1-555-159-7532',
    email: 'george.foster@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '187',
    candidate: 'Hannah Green',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '50000',
    source: 'University Career Fair',
    phone: '+1-555-753-1597',
    email: 'hannah.green@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '190',
    candidate: 'Ian Harris',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '95000',
    source: 'LinkedIn',
    phone: '+1-555-951-3575',
    email: 'ian.harris@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '174',
    candidate: 'Julia Jackson',
    experience: '4',
    noticePeriod: '45',
    currentCTC: '72000',
    source: 'Indeed',
    phone: '+1-555-357-9515',
    email: 'julia.jackson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '167',
    candidate: 'Kevin King',
    experience: '6',
    noticePeriod: '30',
    currentCTC: '88000',
    source: 'Company Website',
    phone: '+1-555-159-3575',
    email: 'kevin.king@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '157',
    candidate: 'Laura Lee',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '62000',
    source: 'Job Fair',
    phone: '+1-555-753-9517',
    email: 'laura.lee@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '181',
    candidate: 'Michael Moore',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '78000',
    source: 'Referral',
    phone: '+1-555-951-7539',
    email: 'michael.moore@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '771',
    candidate: 'Nancy Nelson',
    experience: '8',
    noticePeriod: '60',
    currentCTC: '105000',
    source: 'LinkedIn',
    phone: '+1-555-357-1597',
    email: 'nancy.nelson@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '149',
    candidate: 'Oscar Oliver',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '52000',
    source: 'Job Board',
    phone: '+1-555-159-3577',
    email: 'oscar.oliver@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '009',
    candidate: 'Patricia Parker',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '86000',
    source: 'Recruiter',
    phone: '+1-555-753-3579',
    email: 'patricia.parker@email.com',
    status: 'new',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '006',
    candidate: 'Quentin Quinn',
    experience: '4',
    noticePeriod: '30',
    currentCTC: '70000',
    source: 'Company Website',
    phone: '+1-555-951-1599',
    email: 'quentin.quinn@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '002',
    candidate: 'Rachel Ross',
    experience: '7',
    noticePeriod: '60',
    currentCTC: '92000',
    source: 'LinkedIn',
    phone: '+1-555-357-3579',
    email: 'rachel.ross@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '003',
    candidate: 'Samuel Scott',
    experience: '3',
    noticePeriod: '15',
    currentCTC: '58000',
    source: 'Job Fair',
    phone: '+1-555-159-1599',
    email: 'samuel.scott@email.com',
    status: 'reject',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '088',
    candidate: 'Tina Turner',
    experience: '5',
    noticePeriod: '30',
    currentCTC: '76000',
    source: 'Referral',
    phone: '+1-555-753-1601',
    email: 'tina.turner@email.com',
    status: 'on hold',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
  {
    id: '005',
    candidate: 'Ulysses Underwood',
    experience: '9',
    noticePeriod: '90',
    currentCTC: '120000',
    source: 'Recruiter',
    phone: '+1-555-951-3581',
    email: 'ulysses.underwood@email.com',
    status: 'upCommingInterview',
    screeningDetails: [
      {
        currentlyWorking: 'string',
        experience: 'string',
        companyName: 'string',
        noticePeriod: 'string',
        currentCTC: 'string',
        expectedCTC: 'string',
        project: 'string',
      },
    ],
    interviewDetails: [
      {
        interviewType: 'Face to Face',
        interviewer: 'Daniel Joseph',
        date: '12/03/2024',
        time: '3:00 PM - 4:00 PM',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '655',
    candidate: 'Aswin Krishnan',
    experience: '9',
    noticePeriod: '90',
    currentCTC: '120000',
    source: 'Recruiter',
    phone: '+1-555-951-3581',
    email: 'Aswin.underwood@email.com',
    status: 'upCommingInterview',
    screeningDetails: [
      {
        currentlyWorking: 'string',
        experience: 'string',
        companyName: 'string',
        noticePeriod: 'string',
        currentCTC: 'string',
        expectedCTC: 'string',
        project: 'string',
      },
    ],
    interviewDetails: [
      {
        interviewType: 'Face to Face',
        interviewer: 'Daniel Joseph',
        date: '12/03/2024',
        time: '3:00 PM - 4:00 PM',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '007',
    candidate: 'Victoria Vaughn',
    experience: '2',
    noticePeriod: '30',
    currentCTC: '54000',
    source: 'University Career Fair',
    phone: '+1-555-357-1601',
    email: 'victoria.vaughn@email.com',
    status: 'on hold',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '000',
    candidate: 'William White',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'william.white@email.com',
    status: 'shortlisted',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '121',
    candidate: 'Arjun',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'shortlisted',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
  },
  {
    id: '453',
    candidate: 'Shalini',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'feedback',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
  {
    id: '345',
    candidate: 'Shanu',
    experience: '6',
    noticePeriod: '45',
    currentCTC: '84000',
    source: 'LinkedIn',
    phone: '+1-555-159-3581',
    email: 'arjun.white@email.com',
    status: 'feedback',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    jobPosition: 'Software Engeneer',
    dob: '12/12/2012',
    skills: 'Python , c , C++, Java,Linux',
    education: 'B-tech',
    gender: 'female',
    profileCreatedOn: '12/03/2024',
    screeningDetails: [
      {
        currentlyWorking: 'Yes',
        experience: '2',
        companyName: 'ABCD',
        noticePeriod: '30',
        currentCTC: '300000',
        expectedCTC: '500000',
        project:
          'real time task sheduler , Custom linux moddule for Device controll',
      },
    ],
  },
];

export const demoUsersInfo: UsersInfo[] = [
  {
    id: '122',
    userName: 'John Doe',
    role: 'SuperAdmin',
    designation: 'Chief Technology Officer',
    phoneNumber: '+1 (555) 123-4567',
    emailId: 'john.doe@company.com',
    profileImage:
      'https://images.pexels.com/photos/1462980/pexels-photo-1462980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1  ',
  },
  {
    id: '133',
    userName: 'Jane Smith',
    role: 'HrManager',
    designation: 'Senior HR Manager',
    phoneNumber: '+1 (555) 234-5678',
    emailId: 'jane.smith@company.com',
    profileImage:
      'https://images.pexels.com/photos/3779760/pexels-photo-3779760.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '111',
    userName: 'Mike Johnson',
    role: 'Interviewer',
    designation: 'Senior Software Engineer',
    phoneNumber: '+1 (555) 345-6789',
    emailId: 'mike.johnson@company.com',
    profileImage:
      'https://images.pexels.com/photos/2080383/pexels-photo-2080383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '144',
    userName: 'Sarah Williams',
    role: 'Recruiter',
    designation: 'Talent Acquisition Specialist',
    phoneNumber: '+1 (555) 456-7890',
    emailId: 'sarah.williams@company.com',
    profileImage:
      'https://images.pexels.com/photos/1188047/pexels-photo-1188047.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
  {
    id: '155',
    userName: 'David Brown',
    role: 'Department Head',
    designation: 'Head of Engineering',
    phoneNumber: '+1 (555) 567-8901',
    emailId: 'david.brown@company.com',
    profileImage:
      'https://images.pexels.com/photos/17718199/pexels-photo-17718199/free-photo-of-man-with-black-hair.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  },
];
export const jobs: Job[] = [
  {
    title: 'Robotic Engineer',
    id: 4112,
    totalApplication: 5,
    newApplication: 2,
    activeApplication: 1,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [
      'Conduct detailed dynamic analysis of robotic systems to understand the effects of forces, torques, and loads on motion and stability.',
      'Apply principles of kinematics and dynamics to optimize the performance and efficiency of robotic manipulators and mobile platforms.',
      'Contribute to the mechanical design process, focusing on static force calculations, stress analysis, and robust structural design.',
      'Utilize software tools like MATLAB, and ROS to create, simulate, and validate robotic systems.',
    ],
    skills: [
      'Experience in MATLAB, Python, or equivalent tools for modeling and analysis.',
      'Background in linear systems analysis, stability, and controller design.',
      'Understanding and intuition for the physics of basic motion control systems, kinematics, dynamics, etc.',
      'Excellent problem-solving skills, attention to detail, and strong mathematical abilities.',
      'Proficiency in designing parts and assemblies using 3D modeling software.',
    ],
    jobLink: 'https://www.genrobotics.org/career/roboticengineer',
  },
  {
    title: 'Game Developer',
    id: 4113,
    totalApplication: 15,
    newApplication: 7,
    activeApplication: 3,
    status: 'closed',
    experience: '1-2 years',
    qualification: 'B-Tech in Computer Science or related field',
    responsibilities: [
      'Develop and maintain game code in C++ or similar language.',
      'Work with artists and designers to implement game features.',
      'Optimize game performance for different platforms.',
      'Troubleshoot and debug issues in game code.',
    ],
    skills: [
      'Proficiency in C++ or similar programming languages.',
      'Experience with game engines like Unity or Unreal Engine.',
      'Strong problem-solving and debugging skills.',
      'Knowledge of 3D graphics and game physics.',
    ],
    jobLink: 'https://www.example.com/game-developer',
  },
  {
    title: 'AI/ML Engineer',
    id: 4114,
    totalApplication: 10,
    newApplication: 3,
    activeApplication: 2,
    status: 'new',
    experience: '3-5 years',
    qualification: 'M.Tech in AI/ML or related field',
    responsibilities: [
      'Develop machine learning models and algorithms.',
      'Analyze large datasets to extract meaningful insights.',
      'Collaborate with data scientists and engineers on model implementation.',
      'Stay updated with the latest trends in AI and ML technology.',
    ],
    skills: [
      'Strong programming skills in Python or R.',
      'Experience with machine learning frameworks like TensorFlow or PyTorch.',
      'Solid understanding of algorithms and data structures.',
      'Experience with data analysis and visualization tools.',
    ],
    jobLink: 'https://www.example.com/ai-ml-engineer',
  },
  {
    title: 'Android Developer',
    id: 4115,
    totalApplication: 20,
    newApplication: 10,
    activeApplication: 5,
    status: 'closed',
    experience: '2-4 years',
    qualification: 'B-Tech in Computer Science or related field',
    responsibilities: [
      'Develop and maintain Android applications.',
      'Work with designers to implement user interfaces.',
      'Optimize applications for performance and stability.',
      'Debug and troubleshoot issues in Android applications.',
    ],
    skills: [
      'Proficiency in Java or Kotlin programming languages.',
      'Experience with Android SDK and Android Studio.',
      'Understanding of Android UI/UX principles.',
      'Knowledge of RESTful APIs and integration.',
    ],
    jobLink: 'https://www.example.com/android-developer',
  },
  {
    title: 'Flutter Developer',
    id: 4116,
    totalApplication: 8,
    newApplication: 4,
    activeApplication: 2,
    status: 'new',
    experience: '1-2 years',
    qualification: 'B-Tech in Computer Science or related field',
    responsibilities: [
      'Develop cross-platform mobile applications using Flutter.',
      'Work closely with UI/UX designers to create responsive and attractive interfaces.',
      'Collaborate with backend developers to integrate APIs and services.',
      'Perform code reviews and maintain application quality.',
    ],
    skills: [
      'Proficiency in Dart programming language.',
      'Experience with Flutter SDK and Dart packages.',
      'Knowledge of mobile app development principles and best practices.',
      'Experience with version control systems like Git.',
    ],
    jobLink: 'https://www.example.com/flutter-developer',
  },
  {
    title: 'Linux-Kernel Engineer',
    id: 4117,
    totalApplication: 12,
    newApplication: 6,
    activeApplication: 3,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech in Computer Science or related field',
    responsibilities: [
      'Develop and maintain Linux kernel modules and drivers.',
      'Optimize kernel performance and stability.',
      'Work with the open-source community to contribute to kernel development.',
      'Troubleshoot and debug kernel-related issues.',
    ],
    skills: [
      'Proficiency in C programming language.',
      'Experience with Linux kernel development and debugging.',
      'Strong understanding of operating system concepts.',
      'Knowledge of hardware-software interactions and driver development.',
    ],
    jobLink: 'https://www.example.com/linux-kernel-engineer',
  },

  {
    title: 'Robotic Engineer',
    id: 4112,
    totalApplication: 0,
    newApplication: 0,
    activeApplication: 0,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [
      'Conduct detailed dynamic analysis of robotic systems to understand the effects of forces,torques and loadson motion and stability.',
      'Apply principles of kinematics and dynamics to optimize the performance and efficiency of robotic manipulators and mobile platforms.',
      'Contribute to the mechanical design process, focusing on static force calculations, stress analysis, and robust structural design.',
      'Utilize software tools like MATLAB, and ROS to create, simulate, and validate robotic system.',
    ],
    skills: [
      ' Experience in MATLAB, Python, or equivalent tools for modeling and analysis.',
      'Background in linear systems analysis, stability, and controller design.',
      'Understanding, and intuition for the physics of basic motion control systems, kinematics, dynamics etc.',
      'Excellent problem-solving skills, attention to detail, and strong mathematical abilities.',
      ' Proficiency in designing parts and assemblies using 3D modeling software. ',
    ],
    jobLink: 'https://www.genrobotics.org/career/roboticengineer',
  },
  {
    title: 'Game Developer',
    id: 4112,
    totalApplication: 0,
    newApplication: 0,
    activeApplication: 0,
    status: 'closed',
    experience: '',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'AI/ML Engineer',
    id: 4112,
    totalApplication: 0,
    newApplication: 0,
    activeApplication: 0,
    status: 'closed',
    experience: '',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Android Developer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'closed',
    experience: '',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Flutter Developer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '1-2 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Linux-Kernel Engineer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'UI/UX Designer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: 'Fresher',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'AR/VR Developer',
    id: 4112,
    totalApplication: 0,
    newApplication: 0,
    activeApplication: 0,
    status: 'closed',
    experience: '',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Fullstack Developer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '1-2years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Software Engineer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: 'Fresher',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Mechanical Design Engineer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Production Engineer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '1-2 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Simulation Engineer',
    id: 4112,
    totalApplication: 30,
    newApplication: 4,
    activeApplication: 10,
    status: 'new',
    experience: '2-3 years',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
  {
    title: 'Senior Mechanical Design Engineer',
    id: 4112,
    totalApplication: 0,
    newApplication: 0,
    activeApplication: 0,
    status: 'closed',
    experience: '',
    qualification: 'B-Tech Mechanical Engineering/Mechatronics/Robotics',
    responsibilities: [],
    skills: [],
    jobLink: '',
  },
];

export const singleApplicationData = [
  {
    jobId: 4112,
    stages: [
      {
        stageName: 'stage - 1',
        applications: [
          {
            applicationId: '122',
            cadidateName: 'John Doe',
          },
          {
            applicationId: '122',
            cadidateName: 'John',
          },
        ],
      },
      {
        stageName: 'stage - 2',
        applications: [
          {
            applicationId: '124',
            cadidateName: 'John',
          },
        ],
      },
      {
        stageName: 'stage - 3',
        applications: [
          {
            applicationId: '125',
            cadidateName: 'John Doe',
          },
        ],
      },
    ],
  },
];

export const applicationFormDetails: any[] = [
  {
    applicationId: 122,
    personalInfo: {
      firstName: 'Jhon',
      lastName: 'Doe',
      phone: '12345580',
      email: 'johndoe@hmail.com',
      gender: 'male',
      maritalStatus: 'Single',
      dob: '12/21/2012',
      address: 'Xyz house, Somewhere',
      state: 'Kerala',
      country: 'India',
      pincode: '123456',
    },
    background: [
      {
        educationL: 'Bachelor degree',
        Course: 'B-tech',
        specilization: 'AL & ML',
        duration: '4 year',
      },
    ],
    experience: [
      {
        companyName: 'XYZ',
        designation: 'ML engeneer',
        duration: '2 year',
      },
    ],
    noticePeriod: '30days',
    skills: 'Python , c , C++, Java,Linux',
    links: 'https://www.google.com',
    resumeURL: 'https://pdfobject.com/pdf/sample.pdf',
    initalScreeningDetails: [
      {
        experience: '2 year',
        noticePeriod:'30 days',
        currentCtc:'200000',
        expectedCtc:'40000',
        currentlyWorking:'yes',
        companyName:'Xyz'
      },
    ],
    feedbacks: [
      {
        interviewType: 'assessment',
        star: '4',
        remarks: 'write something about the candidate performance',
      },
      {
        interviewType: 'face to face',
        star: '4',
        remarks: 'write something about the candidate performance',
      },
    ],
  },
];
